DataBiosphere/terra-azure-relay-listeners

README.md, service/src/main/java/org/broadinstitute/listener/config/AppConfiguration.java, service/src/main/java/org/broadinstitute/listener/config/ListenerProperties.java, service/src/main/java/org/broadinstitute/listener/relay/http/ListenerConnectionHandler.java, service/src/main/java/org/broadinstitute/listener/relay/http/RelayedHttpRequestProcessor.java, service/src/main/java/org/broadinstitute/listener/relay/inspectors/HeaderLoggerInspector.java, service/src/main/java/org/broadinstitute/listener/relay/inspectors/InspectorLocator.java, service/src/main/java/org/broadinstitute/listener/relay/inspectors/InspectorType.java, service/src/main/java/org/broadinstitute/listener/relay/inspectors/InspectorsProcessor.java, service/src/main/java/org/broadinstitute/listener/relay/inspectors/RequestInspector.java, service/src/main/java/org/broadinstitute/listener/relay/transport/RelayedRequestPipeline.java, service/src/main/java/org/broadinstitute/listener/relay/wss/WebSocketConnectionsHandler.java, service/src/main/resources/application.yml, service/src/test/java/org/broadinstitute/listener/relay/http/ListenerConnectionHandlerTest.java, service/src/test/java/org/broadinstitute/listener/relay/http/RelayedHttpRequestProcessorTest.java, service/src/test/java/org/broadinstitute/listener/relay/inspectors/InspectorsProcessorTest.java, service/src/test/java/org/broadinstitute/listener/relay/transport/RelayedRequestPipelineTest.java, service/src/test/java/org/broadinstitute/listener/relay/wss/WebSocketConnectionsHandlerTest.java
- Enables the implementation of request inspectors.
- The request inspectors:
- Can accept or reject HTTP relayed requests from the client.
- Can be enabled or disabled via configuration.
- The PR includes an implementation that logs the HTTP headers for all the requests.
=> [PR TOAZ-82] Request inspectors 

service/src/main/java/org/broadinstitute/listener/relay/http/RelayedHttpRequestProcessor.java
Issue Description: Currently the HTTP client is not configured to a specific HTTP version. Which results on following issues:
HTTP 2 returns headers that are not accepted by Azure Relay.
The HTTP client fails to read the response body from the target.   
Resolution:
Configure the default HTTP client to use HTTP 1.1.
=> [TOA-139] Fix - Internal HTTP client defaults to HTTP 1.1

service/src/main/java/org/broadinstitute/listener/relay/http/ListenerConnectionHandler.java, service/src/main/java/org/broadinstitute/listener/relay/http/RelayedHttpRequestProcessor.java, service/src/main/java/org/broadinstitute/listener/relay/http/TargetHttpResponse.java, service/src/test/java/org/broadinstitute/listener/relay/http/RelayedHttpRequestProcessorTest.java, service/src/test/java/org/broadinstitute/listener/relay/http/TargetHttpResponseTest.java
Issue Description: When a request to the target endpoint fails, the listener must send a 500 response to the caller. Instead, the caller is receiving gateway time out error from Azure Relay. 
Root cause: The error handling of the listener is not properly closing the relayed response body when target endpoint fails to be called. The relayed response is not closed because the body does not contain any content. Azure Relay eventually times out the request, and the caller receives a timeout error instead of a 500 response. 
Resolution: Add content to the response body so the relayed response is close properly.  Make sure the target response is always closed.
=> [TOAZ-140] Fix: Return a HTTP 500 response when requests to the target fail. 

README.md, service/src/main/java/org/broadinstitute/listener/config/TargetProperties.java, service/src/main/java/org/broadinstitute/listener/relay/transport/DefaultTargetResolver.java, service/src/test/java/org/broadinstitute/listener/relay/transport/DefaultTargetResolverTest.java
Issue Description: The listener adds the hybrid connection name (Entity Path) to the target URL. This behavior enables browser redirects for Jupyter. However, for APIs or other endpoints that don’t require redirection, this functionality may result in invalid requests. You can’t disable this functionality.  
Root Cause: The implementation has a flag that turns this functionality on and off, however it is not exposed as configuration property.
Resolution: Expose `removeEntityPath` as a configuration property, with a default of `false`
=> [TOAZ-142] Remove hybrid connection name from the HTTP request to the target

README.md, service/src/main/java/org/broadinstitute/listener/config/AppConfiguration.java, service/src/main/java/org/broadinstitute/listener/config/SamInspectorProperties.java, service/src/main/java/org/broadinstitute/listener/relay/inspectors/SamResourceClient.java, service/src/main/resources/application.yml, service/src/test/java/org/broadinstitute/listener/relay/inspectors/SamResourceClientTest.java
I tested this by deploying it to our Cromwell app using the changes in https://github.com/broadinstitute/cromwhelm/pull/31 and configuring it to use workspace access when checking permission.
Unsure whether retaining the old sam resource type value as a default is valuable, I just didn't want Leo's use of this to break.
=> BT-654 Make Sam resource type configurable

service/src/main/java/org/broadinstitute/listener/config/CorsSupportProperties.java, service/src/main/java/org/broadinstitute/listener/relay/http/RelayedHttpRequestProcessor.java, service/src/main/java/org/broadinstitute/listener/relay/http/TargetHttpResponse.java, service/src/main/resources/application.yml, service/src/test/java/org/broadinstitute/listener/relay/http/RelayedHttpRequestProcessorTest.java, service/src/test/java/org/broadinstitute/listener/relay/http/TargetHttpResponseTest.java, service/src/test/java/org/broadinstitute/listener/relay/transport/RelayedRequestPipelineTest.java
https://broadworkbench.atlassian.net/browse/IA-3490
* Add `content-security-policy` in responses
* Append `Secure; SameSite=None` in jupyterlab's set-cookie response header
Tested locally and things are working finally!
=> IA-3490 add CSP in responses

README.md, service/src/main/java/org/broadinstitute/listener/config/TargetProperties.java, service/src/main/java/org/broadinstitute/listener/config/TargetRoutingRule.java, service/src/main/java/org/broadinstitute/listener/relay/http/RelayedHttpRequestProcessor.java, service/src/main/java/org/broadinstitute/listener/relay/transport/DefaultTargetResolver.java, service/src/main/java/org/broadinstitute/listener/relay/transport/TargetResolver.java, service/src/main/java/org/broadinstitute/listener/relay/transport/TargetRule.java, service/src/main/java/org/broadinstitute/listener/relay/transport/TargetURIParser.java, service/src/main/resources/application.yml, service/src/test/java/org/broadinstitute/listener/relay/transport/DefaultTargetResolverTest.java, service/src/test/java/org/broadinstitute/listener/relay/transport/TargetURIParserTest.java
- The listener supports routing to targets based on configuration of rules.
- A rule contains a `containsPath` String and the `targetHost`
- Documentation update with samples.
=> IA-3698 Implementation of routing rules

service/src/main/java/org/broadinstitute/listener/relay/Utils.java, service/src/main/java/org/broadinstitute/listener/relay/http/RelayedHttpRequestProcessor.java, service/src/main/java/org/broadinstitute/listener/relay/http/TargetHttpResponse.java
https://broadworkbench.atlassian.net/browse/IA-3698
We need CORS headers for welder as well..Previously we're only adding these headers for preflight and setCookie call. But we need it for all relayed requests in order for the requests to succeed in browser
Tested launching jupyterlab from Terra UI
=> IA-3698 add CORS headers

README.md, service/src/main/java/org/broadinstitute/listener/config/AppConfiguration.java, service/src/main/java/org/broadinstitute/listener/config/SamInspectorProperties.java, service/src/main/java/org/broadinstitute/listener/relay/http/RelayedHttpRequestProcessor.java, service/src/main/java/org/broadinstitute/listener/relay/inspectors/SamPermissionInspector.java, service/src/main/java/org/broadinstitute/listener/relay/inspectors/SamResourceClient.java, service/src/main/resources/application.yml, service/src/test/java/org/broadinstitute/listener/relay/http/RelayedHttpRequestProcessorTest.java, service/src/test/java/org/broadinstitute/listener/relay/http/TargetHttpResponseTest.java, service/src/test/java/org/broadinstitute/listener/relay/inspectors/ExpiresAtCacheTest.java, service/src/test/java/org/broadinstitute/listener/relay/inspectors/SamResourceClientTest.java
- Added the `listener.samInspectorProperties.samAction` config property, with a default value of `write`
- Fixed tests that were not passing prior to the change.
=> [TOAZ-242]  Makes sam action configurable, and tests fixes.

service/src/main/java/org/broadinstitute/listener/relay/http/ListenerConnectionHandler.java, service/src/main/java/org/broadinstitute/listener/relay/transport/RelayedRequestPipeline.java, service/src/test/java/org/broadinstitute/listener/relay/transport/RelayedRequestPipelineTest.java
- The cause of the issue was a blocking condition encountered when the SDK flushes/closes the connection after a PUT operation. 
- This PR configures the reactive pipeline not to use the default thread pool.
=> [AJ-805] File uploads block subsequent requests when using Jupyter labs 

service/src/main/java/org/broadinstitute/listener/relay/transport/RelayedRequestPipeline.java
Long-lasting requests through the relay listener were blocking subsequent requests to the same service.   Seems the listener was not using the scheduler as expected; this PR forces it to do so.
=> AJ-869 fix blocking calls

README.md, service/build.gradle, service/src/main/java/org/broadinstitute/listener/config/AppConfiguration.java, service/src/main/java/org/broadinstitute/listener/config/ListenerProperties.java, service/src/main/java/org/broadinstitute/listener/config/SetDateAccessedInspectorProperties.java, service/src/main/java/org/broadinstitute/listener/relay/inspectors/InspectorType.java, service/src/main/java/org/broadinstitute/listener/relay/inspectors/SetDateAccessedInspector.java, service/src/main/java/org/broadinstitute/listener/relay/inspectors/SetDateAccessedInspectorOptions.java, service/src/main/java/org/broadinstitute/listener/relay/transport/RelayedRequestPipeline.java, service/src/main/resources/application.yml, service/src/test/java/org/broadinstitute/listener/relay/inspectors/SetDateAccessedInspectorTest.java
This PR includes the following:
- New listener inspector `SetAccessedDateInspector` that calls Leo using the user auth token when a request is received within a window.
- At the most 1 request to Leo is made within a given window if more requests are received.
- The inspector won't block the request if the call to Leo fails. 
- Refactoring, inspectors are now executed in the same thread as the request to the local endpoint and not on the main thread. 
- Updated documentation with configuration values for the new inspector.
=> [IA-4125] Set accessed date via inspector

service/src/main/java/org/broadinstitute/listener/relay/inspectors/SetDateAccessedInspector.java, service/src/main/java/org/broadinstitute/listener/relay/transport/RelayedRequestPipeline.java
https://broadworkbench.atlassian.net/browse/TOAZ-325
I've noticed this error several times deploying k8s apps:
```
2023-04-21 21:11:18.634  ERROR 1 --- [oundedElastic-5] reactor.core.publisher.Operators         : Operator called default onErrorDropped
reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.ClassCastException: class reactor.core.publisher.MonoEmpty cannot be cast to class org.broadinstitute.listener.relay.http.TargetHttpResponse (reactor.core.publisher.MonoEmpty is in unnamed module of loader 'app'; org.broadinstitute.listener.relay.http.TargetHttpResponse is in unnamed module of loader org.springframework.boot.devtools.restart.classloader.RestartClassLoader @14534429)
Caused by: java.lang.ClassCastException: class reactor.core.publisher.MonoEmpty cannot be cast to …
```
=> [TOAZ-325] Fix ClassCastException when processing requests

.github/pull_request_template.md, service/src/main/java/org/broadinstitute/listener/config/CorsSupportProperties.java, service/src/main/java/org/broadinstitute/listener/relay/Utils.java, service/src/main/java/org/broadinstitute/listener/relay/http/RelayedHttpRequestProcessor.java, service/src/main/java/org/broadinstitute/listener/relay/http/TargetHttpResponse.java, service/src/main/resources/application.yml, service/src/test/java/org/broadinstitute/listener/relay/UtilTest.java, service/src/test/java/org/broadinstitute/listener/relay/http/RelayedHttpRequestProcessorTest.java, service/src/test/java/org/broadinstitute/listener/relay/http/TargetHttpResponseTest.java
__Jira ticket__: https://broadworkbench.atlassian.net/browse/IA-4081
Leo PR:
https://github.com/DataBiosphere/leonardo/pull/3311
- Update reference.conf to point to the image generated from the TARL PR
- Security vulnerability with request headers.
- Inspect headers on a request with a Cookie, and confirm it ends with 'HttpOnly'
- Inspect headers on a relayed HTTP request and confirm AccessControlAllowOrigin is '*'
How to test:
Check out on your bee and deploy the Leo image for the branch `IA-4081-update-azure-relay-listeners` version hash `74fb80a9a19b` using the terra helmfile version: `0.169.101`. Details of this helmfile version can be found here: https://github.com/broadinstitute/terra-helmfile/pull/4184 
The helmfile changes remove the wildcard from the allowed hosts, which …
=> [IA-4082] Update access control allow origin and cookie.

service/src/main/java/org/broadinstitute/listener/relay/inspectors/GoogleTokenInfoClient.java
This [commit](https://github.com/DataBiosphere/terra-azure-relay-listeners/commit/3b326be64f0c7be9ac5155e44dd49b510ff3fa1e) introduced enhanced logging for the azure relay listener. There was also an @ cacheable  annotation errantly included [here](https://github.com/DataBiosphere/terra-azure-relay-listeners/blob/3b326be64f0c7be9ac5155e44dd49b510ff3fa1e/service/src/main/java/org/broadinstitute/listener/relay/inspectors/GoogleTokenInfoClient.java#L18). Since this cache is not configured in the spring app config, the listener fails to startup and relay requests fail. 
This annotation was errantly added during development and not needed afaict. 
Tested in a BEE:
1. Spun up WDS, imported data to a table successfully
2. Spun up a VM, turned on a Jupyter notebook and did a print("Hello world") …
=> [WOR-1043] Remove cacheable annotation

service/src/main/java/org/broadinstitute/listener/relay/inspectors/SetDateAccessedInspector.java
Leo PR: https://github.com/DataBiosphere/leonardo/pull/3402
Call the correct endpoint on leo (`updateDateAccessed`) and correctly parse the token from the initial request (looking in both Cookie and Authorization headers).
=> [IA-4283] Set dateAccessed from listener properly

service/src/main/java/org/broadinstitute/listener/config/CorsSupportProperties.java, service/src/main/java/org/broadinstitute/listener/relay/Utils.java, service/src/test/java/org/broadinstitute/listener/relay/UtilTest.java
- Added functionality to allow port to be part of the URL schema. Added a test to verify.
- Requests were being denied if they were from localhost:3000
=> [IA-4404] isValidOrigin - Added unit test and updated logic.

service/src/main/resources/application.yml
**_Reviewer_**: the latest version of this PR reduces the cache TTL to 90 seconds. What is your opinion of an appropriate TTL? Should we disable the cache entirely?
Change the Sam caching eviction strategy:
* 1 hr TTL -> 90 second TTL
* expireAfterAccess -> expireAfterWrite
The expireAfterAccess -> expireAfterWrite change means that Sam responses "should be automatically removed from the cache once a fixed duration has elapsed after the entry’s creation, or the most recent replacement of its value" instead of being "automatically removed from the cache once a fixed duration has elapsed after the entry’s creation, the most recent replacement of its value, or its last read." (reference https://camel.apache.org/components/3.20.x/caffeine-cache-component.html#_component_options)
In other …
=> AJ-1147: cache Sam responses much less aggressively

.github/workflows/publish.yml, .gitignore, README.md, build.gradle, service/build.gradle
Run SonarCloud analysis, with jacoco coverage data, from gradle in the unit-tests job. Results are shown in the PR  and [on SonarCloud](https://sonarcloud.io/project/overview?id=DataBiosphere_terra-azure-relay-listeners).
=> DSEC-688 sonar static analysis

.github/workflows/publish.yml, service/spring.gradle, service/src/main/java/org/broadinstitute/listener/config/AppConfiguration.java, service/src/main/java/org/broadinstitute/listener/relay/Utils.java, service/src/main/java/org/broadinstitute/listener/relay/http/AvailabilityListener.java, service/src/main/java/org/broadinstitute/listener/relay/http/ListenerConnectionHandler.java, service/src/main/java/org/broadinstitute/listener/relay/http/RelayedHttpRequestProcessor.java, service/src/main/java/org/broadinstitute/listener/relay/transport/RelayedRequestPipeline.java, service/src/main/resources/application.yml, service/src/test/java/org/broadinstitute/listener/relay/http/AvailabilityTest.java, service/src/test/java/org/broadinstitute/listener/relay/http/RelayedHttpRequestProcessorTest.java, service/src/test/java/org/broadinstitute/listener/relay/inspectors/ExpiresAtCacheTest.java, service/src/test/java/org/broadinstitute/listener/relay/transport/RelayedRequestPipelineTest.java, service/src/test/resources/application-test.yml
Enable [Spring Boot Actuator](https://www.baeldung.com/spring-liveness-readiness-probes) to set up liveness and readiness probes in Spring Boot. These are configured in the Relay Listener helm chart in: https://github.com/broadinstitute/terra-helmfile/pull/4411.
The Spring Boot endpoints in the relay listener are not exposed externally. Additionally I added a `/listenerstatus` endpoint through the Relay Namespace, which also returns the actuator health endpoint payload.
Deployed via a BEE. Verified:
1. Listener pods come up, k8s events show liveness/readiness working
2. Listener logs show liveness/readiness state changes
3. `/listenerstatus` endpoint works
4. Leo metrics are populated with listener health
=> AJ-1083: Add liveness and readiness checks via Spring actuator

service/src/main/java/org/broadinstitute/listener/config/AppConfiguration.java, service/src/main/java/org/broadinstitute/listener/relay/http/AvailabilityListener.java, service/src/main/java/org/broadinstitute/listener/relay/http/ListenerConnectionHandler.java, service/src/main/java/org/broadinstitute/listener/relay/http/RelayedHttpRequestProcessor.java, service/src/main/java/org/broadinstitute/listener/relay/inspectors/SamResourceClient.java, service/src/main/java/org/broadinstitute/listener/relay/transport/RelayedRequestPipeline.java, service/src/test/java/org/broadinstitute/listener/relay/http/RelayedHttpRequestProcessorTest.java, service/src/test/java/org/broadinstitute/listener/relay/inspectors/SamResourceClientTest.java, service/src/test/java/org/broadinstitute/listener/relay/transport/RelayedRequestPipelineTest.java
JIRA: https://broadworkbench.atlassian.net/browse/IA-4489
- Add `SamResourceClient.isUserEnabled` method and call it from the `setCookie` endpoint
- Added unit test coverage for `setCookie`
- Improvements to `SamResourceClient` -- instantiate a new client for each request but use shared thread pool
- During security review, determined that `setCookie` was not validating Terra user enablement/ToS. We previously fixed a similar issue in the Leo-proxy implementation of `setCookie`.
- ✅  Unit test coverage of setCookie for enabled/disabled users
- (TODO) test on a BEE
=> IA-4489: setCookie endpoint should check user enablement and ToS

service/src/main/java/org/broadinstitute/listener/config/AppConfiguration.java, service/src/main/java/org/broadinstitute/listener/relay/inspectors/SamResourceClient.java, service/src/test/java/org/broadinstitute/listener/relay/inspectors/SamResourceClientTest.java
- Check whether a user is in the right workspace when trying to access an app or notebook
- When app owner is removed from a workspace, they lose access to their app APIs
Tested it in a BEE by updating the Relay Listener image Leo points to. Testing steps:
- User A creates a workspace and Cromwell app
- User A is able to see Cromwell app and access its APIs
- User A adds User B as owner on the workspace
- User B removes User A from the workspace
- User A can no longer access the workspace or Cromwell app APIs. Relay listener returns 403 on the request:
```
% curl -i -X 'GET' \
'https://lz1...../cbas/api/batch/v1/methods?show_versions=false' \
-H 'accept: application/json' \
-H 'Authorization: Bearer <redacted>'
HTTP/1.1 403 The listener rejected the request. Tracking ID:2aa...
Via: 1.1 …
```
=> [WM-2157] Additional check for workspace access

service/src/main/java/org/broadinstitute/listener/config/AppConfiguration.java, service/src/main/java/org/broadinstitute/listener/relay/health/HybridConnectionListenerHealth.java, service/src/main/resources/application.yml, service/src/test/java/org/broadinstitute/listener/relay/http/AvailabilityTest.java
Adds a new `hybridConnectionListenerHealth` health check, via Actuator, to the k8s liveness probe. This health check echoes the state of `HybridConnectionListener.isOnline()`, which is part of the `azure-relay` library.
It seems that if the listener runs into certain errors - specifically, we've seen problems with `java.util.concurrent.TimeoutException: DNS timeout 15000 ms` - the listener's connections hang and stop responding.
This PR adds the listener's online state to the actuator health check. In theory, this would allow k8s to kill the listener pod and restart a new pod. This is drastic, but it could kick the listener connection back to a good place.
-
=> AJ-1550: logging and health check for HybridConnectionListener

service/src/main/java/org/broadinstitute/listener/StartupHandler.java, service/src/main/java/org/broadinstitute/listener/relay/ListenerException.java, service/src/main/java/org/broadinstitute/listener/relay/http/ListenerConnectionHandler.java, service/src/main/java/org/broadinstitute/listener/relay/transport/RelayedRequestPipeline.java, service/src/test/java/org/broadinstitute/listener/relay/http/AvailabilityTest.java
* Trap exceptions in the StartupHandler. If startup fails, set liveness state to broken so k8s will restart the pod.
* Change a few logging statements from debug to info for increased visibility.
It seems that if the listener runs into certain errors - specifically, we've seen problems with java.util.concurrent.TimeoutException: DNS timeout 15000 ms - the listener never connects to Relay, but startup still continues and liveness/readiness remain ok. This leaves the listener in a non-functional state (it isn't listening for requests) eternally.
=> AJ-1550: handle errors during startup

service/spring.gradle
Disable `devtools` in the listener. Slack thread: https://broadinstitute.slack.com/archives/C05BYVBM2HE/p1707757014406499
- `devtools` was mistakenly enabled in the live/prod deployment of the listener, due to an interaction with `jib`. This was causing slower startup and restarts in listener deployments.
I found this when I was testing stuff in a UAE region. `devtools` was kicking in and restarting the Listener (maybe because I was mistakenly using a smaller machine type). I don't think people use `devtools` locally anyway, so let's just remove it. Note WDS did the same: https://github.com/DataBiosphere/terra-workspace-data-service/pull/334
=> [TOAZ-340] Remove spring-boot devtools

service/src/main/java/org/broadinstitute/listener/config/AppConfiguration.java, service/src/main/java/org/broadinstitute/listener/relay/inspectors/SamResourceClient.java, service/src/test/java/org/broadinstitute/listener/relay/inspectors/SamResourceClientTest.java
* Removes the `READ` check for workspace access
- We do not want a workspace read check as that will not succeed for the Leonardo SA when an auth domain is present on the workspace
[Related doc](https://docs.google.com/document/d/16Gfjxx4QH2IiTSDUgIb5hzMtOlI4i62_-5NVjBDO8kY/edit#heading=h.4dgk7j6qvmuw)
- Leo uses it's own SA identity to poll on resource operations within an MRG, such as welder and jupyter. However, `READ` is auth domain constrainable. When an auth domain is applied to the workspace, the `SamResourceClient`'s  `READ` check will fail and Leo will not be able to perform the needed operations. Since there is [no longer](https://github.com/DataBiosphere/leonardo/pull/3488) a direct policy applied to apps in a workspace, the inheritance from the workspace will be enough to …
=> [WOR-1517] Remove workspace-level READ check 

service/src/main/java/org/broadinstitute/listener/relay/http/RelayedHttpRequestProcessor.java, service/src/main/resources/application.yml, service/src/test/java/org/broadinstitute/listener/relay/http/RelayedHttpRequestProcessorTest.java, service/src/test/resources/sample-text.txt
Eliminate code that materializes the entire HTTP response body into a Java variable; hopefully this eliminates OutOfMemory errors in the listener.
When writing the HTTP response to the caller, the previous code used `InputStream.readAllBytes()`, which creates a single byte array containing the entire HTTP response. In this PR, we use `StreamUtils.copy` instead, which works in 4096-byte buffers. Each buffer is read from the response, written to the caller, and then discarded.
We have seen multiple instances of the listener crashing with OOMs, especially when WDS has a large response such as a TSV file. This code change is a hopeful fix for that.
=> IA-4893: don't materialize the entire response
